# Generated by Django 2.2.5 on 2019-09-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunny_poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FilePathField(path='/static/img'),
        ),
    ]
