# Generated by Django 2.2.5 on 2019-09-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunny_poster', '0003_auto_20190904_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
    ]
