# Generated by Django 2.2.5 on 2019-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunny_poster', '0005_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
