# Generated by Django 2.2.5 on 2019-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunny_poster', '0006_auto_20190904_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
